__include__: ['./_base_transformer.yml']

output_dir: ./output/ablation/70_d0_transformer_nolowrank

RTDETR:
  encoder_return_aux: False
  encoder_compute_rank_loss_in_eval: False
  encoder_return_attn_maps: False

RTDETRCriterionv2:
  losses: ['vfl', 'boxes']
  weight_dict:
    loss_vfl: 1.0
    loss_bbox: 5.0
    loss_giou: 2.0
