__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/htsat.yml',
  './include/optimizer.yml'
]

output_dir: ./output/rtdetrv2_eghtsat2_120e


# =====================================================
# Model
# =====================================================

task: detection

model: RTDETR
criterion: RTDETRCriterionv2
postprocessor: RTDETRPostProcessor

use_focal_loss: True
eval_spatial_size: [128, 256]


RTDETR:
  backbone: EGHTSATBackbone
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2


# =====================================================
# Backbone
# =====================================================

EGHTSATBackbone:
  in_chans: 1
  embed_dim: 192
  depths: [2, 2, 24, 2]
  num_heads: [6, 12, 24, 48]
  # 确保返回第 1,2,3 层 (索引)
  return_idx: [1, 2, 3]


# =====================================================
# Encoder
# =====================================================

HybridEncoder:
  in_channels: [384, 768, 1536]
  feat_strides: [8, 16, 32]

  hidden_dim: 384
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1536
  dropout: 0.
  enc_act: 'gelu'

  expansion: 1.0
  depth_mult: 1
  act: 'silu'


# =====================================================
# Decoder
# =====================================================

RTDETRTransformerv2:
  feat_channels: [384, 384, 384]
  feat_strides: [8, 16, 32]
  hidden_dim: 384
  num_levels: 3

  num_layers: 6
  num_queries: 100

  num_denoising: 50
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  eval_idx: -1

  num_points: [4, 4, 4]
  cross_attn_method: default
  query_select_method: default


# =====================================================
# Training
# =====================================================

epoches: 300


optimizer:
  type: AdamW

  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00003
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00003
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# =====================================================
# Data Loader
# =====================================================

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 117
  collate_fn:
    stop_epoch: 117